### ISSUE TITLE
Can add windows support for windows R env though WSL

### ISSUE THREAD

**Issue by zhang919** [PhanstielLab/bedtoolsr#6]
Dear,
Thanks for development bedtoolsr, Its really useful. According to Microsoft's documentation, it is actually feasible to directly call bedtools in wsl in wihdows R by options(bedtools.path = "wsl /home/username/miniconda3/bin/"). You can easily test it in poweshell by wsl /the/path/to/your/bedtools/in/wsl/ . But the temp file path in bedtoolsr is incompatible. Could you please add a patch to support it.
Best.
Zhang

**Comment by cwenger** [comment]
Hi Zhang,

Sorry for the long delay in getting back to you, I had accidentally unwatched the repository.

I'm not sure if the temp path is actually the issue, but rather calling bedtools in WSL from Windows. For example, running this on Windows:

`wsl /usr/bin/bedtools -a A.bed -b B.bed > C.bed`

gives:

`error: unrecognized command: -a`

because it interprets the -a as an argument to WSL rather than bedtools. I thought maybe you could run WSL with -e and the whole bedtools call in quotes. That eliminates the error but doesn't seem to produce any output.

Perhaps you are more experienced with WSL and can suggest a workaround?

**Comment by cwenger** [comment]
In my previous comment I left out `intersect` in the call. I see now that it could potentially work and you are correct about the issue with temp filepaths. However, I'm not sure if there is a clean way to allow this without writing special logic for WSL. Assuming the user specifies a Windows-style filepath, bedtoolsr would have to know to convert it to a WSL-compatible filepath.

**Comment by cwenger** [comment]
I went ahead and added the WSL-specific logic. Give it a try and let me know if it works for you.

**Comment by HuGang-c** [comment]
Hi, sorry to re-open this,

I would like to try the WSL-specific logic bedtoolsr, however, I can't find how to operate it, can you explain？

**Comment by cwenger** [comment]
Hi @HuGang-c, WSL support is included in the latest release. Just do everything as you normally would except under WSL, and open an issue if you run into specific problems.
